version: '3.8'
services:
  db:
    image: postgres:16.0-alpine3.18
    container_name: splinter_db
    ports:
      - "5432:5432"
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: splinter_db

  server:
    image: golang:1.21.1-alpine3.18
    volumes:
      - ./server:/server
    working_dir: /server
    ports:
      - 8080:8080
    command: ["/bin/sh", "-c", "apk add make && make run"]
